services:
  - type: web
    name: access-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --worker-class aiohttp.GunicornWebWorker
    envVars:
      - key: PORT
        value: "8080"
      - key: PYTHON_VERSION
        value: "3.11.6"
